Partially refactor code and add improvements
apontini/jirawatch pull request #11
Opened 2020-09-18 07:09 UTC by apontini

Code has been partially refactored to clean eerything up a bit. Moreover, a check for the -t parameter has been added and issue name will be printed when starting tracking. This solves #8 and #9

2020-09-18 15:23 UTC, Polpetta approved these changes

2020-09-22 06:49 UTC, federicorispo requested changes

2020-09-22 06:49 UTC, federicorispo commented on lib/jirawatch/cli/track.rb
> +        puts Jirawatch.strings.tracking_cli % [issue_key, issue.attrs["fields"]["summary"], tracking_started_at.strftime("%Y-%m-%d %H:%M:%S")]
Can you add more information about the issue? (some hint: time original estimate, time already logged and by who)

2020-10-19 16:46 UTC, apontini commented on lib/jirawatch/cli/track.rb
> +        puts Jirawatch.strings.tracking_cli % [issue_key, issue.attrs["fields"]["summary"], tracking_started_at.strftime("%Y-%m-%d %H:%M:%S")]
done!

2020-10-19 16:49 UTC, federicorispo approved these changes

2020-10-19 16:50 UTC, merged